sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t dockerjw20/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true dockerjw20/docker-react npm run test